"04-Jan-24 00:37:04" : numexpr.utils : INFO : NumExpr defaulting to 4 threads.
"04-Jan-24 00:37:04" : root : INFO : run_presc_pipeline.py is started...
"04-Jan-24 00:37:04" : root : INFO : main() is started...
"04-Jan-24 00:37:04" : create_objects : INFO : get_spark_object() is started. The 'Prod' env is used.
"04-Jan-24 00:37:26" : create_objects : INFO : Spark Object is created
"04-Jan-24 00:37:33" : validations : INFO : Validate the spark object by printing current date : [Row(current_date()=datetime.date(2024, 1, 4))]
"04-Jan-24 00:37:33" : validations : INFO : Spark object is validated and it is ready
"04-Jan-24 00:37:33" : root : ERROR : Error occurred in the main() method. [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
Traceback (most recent call last):
  File "/home/hadoop/Documents/BigData-Project-End-to-End/src/main/python/bin/run_presc_pipeline.py", line 38, in main
    for file in os.listdir(gav.staging_dim_path):
FileNotFoundError: [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
"04-Jan-24 00:39:09" : numexpr.utils : INFO : NumExpr defaulting to 4 threads.
"04-Jan-24 00:39:10" : root : INFO : run_presc_pipeline.py is started...
"04-Jan-24 00:39:10" : root : INFO : main() is started...
"04-Jan-24 00:39:10" : create_objects : INFO : get_spark_object() is started. The 'Prod' env is used.
"04-Jan-24 00:39:33" : create_objects : INFO : Spark Object is created
"04-Jan-24 00:39:40" : validations : INFO : Validate the spark object by printing current date : [Row(current_date()=datetime.date(2024, 1, 4))]
"04-Jan-24 00:39:40" : validations : INFO : Spark object is validated and it is ready
"04-Jan-24 00:39:40" : root : ERROR : Error occurred in the main() method. [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
Traceback (most recent call last):
  File "/home/hadoop/Documents/BigData-Project-End-to-End/src/main/python/bin/run_presc_pipeline.py", line 38, in main
    for file in os.listdir(gav.staging_dim_path):
FileNotFoundError: [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
"04-Jan-24 00:43:00" : numexpr.utils : INFO : NumExpr defaulting to 4 threads.
"04-Jan-24 00:43:00" : root : INFO : run_presc_pipeline.py is started...
"04-Jan-24 00:43:00" : root : INFO : main() is started...
"04-Jan-24 00:43:00" : create_objects : INFO : get_spark_object() is started. The 'Prod' env is used.
"04-Jan-24 00:43:23" : create_objects : INFO : Spark Object is created
"04-Jan-24 00:43:31" : validations : INFO : Validate the spark object by printing current date : [Row(current_date()=datetime.date(2024, 1, 4))]
"04-Jan-24 00:43:31" : validations : INFO : Spark object is validated and it is ready
"04-Jan-24 00:43:31" : root : ERROR : Error occurred in the main() method. [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
Traceback (most recent call last):
  File "/home/hadoop/Documents/BigData-Project-End-to-End/src/main/python/bin/run_presc_pipeline.py", line 38, in main
    for file in os.listdir(gav.staging_dim_path):
FileNotFoundError: [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
"04-Jan-24 00:45:35" : numexpr.utils : INFO : NumExpr defaulting to 4 threads.
"04-Jan-24 00:45:35" : root : INFO : run_presc_pipeline.py is started...
"04-Jan-24 00:45:35" : root : INFO : main() is started...
"04-Jan-24 00:45:35" : create_objects : INFO : get_spark_object() is started. The 'Prod' env is used.
"04-Jan-24 00:45:59" : create_objects : INFO : Spark Object is created
"04-Jan-24 00:46:06" : validations : INFO : Validate the spark object by printing current date : [Row(current_date()=datetime.date(2024, 1, 4))]
"04-Jan-24 00:46:06" : validations : INFO : Spark object is validated and it is ready
"04-Jan-24 00:46:06" : root : ERROR : Error occurred in the main() method. [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
Traceback (most recent call last):
  File "/home/hadoop/Documents/BigData-Project-End-to-End/src/main/python/bin/run_presc_pipeline.py", line 38, in main
    for file in os.listdir(gav.staging_dim_path):
FileNotFoundError: [Errno 2] No such file or directory: '/user/hadoop/Projects/PrescPipeline/staging/Dim'
"04-Jan-24 00:47:12" : numexpr.utils : INFO : NumExpr defaulting to 4 threads.
"04-Jan-24 00:47:12" : root : INFO : run_presc_pipeline.py is started...
"04-Jan-24 00:47:12" : root : INFO : main() is started...
"04-Jan-24 00:47:12" : create_objects : INFO : get_spark_object() is started. The 'Prod' env is used.
"04-Jan-24 00:47:35" : create_objects : INFO : Spark Object is created
"04-Jan-24 00:47:43" : validations : INFO : Validate the spark object by printing current date : [Row(current_date()=datetime.date(2024, 1, 4))]
"04-Jan-24 00:47:43" : validations : INFO : Spark object is validated and it is ready
"04-Jan-24 00:47:43" : root : ERROR : Error occurred in the main() method. [Errno 2] No such file or directory: 'hdfs://localhost:9000/user/hadoop/Projects/PrescPipeline/staging/Dim'
Traceback (most recent call last):
  File "/home/hadoop/Documents/BigData-Project-End-to-End/src/main/python/bin/run_presc_pipeline.py", line 38, in main
    for file in os.listdir(gav.staging_dim_path):
FileNotFoundError: [Errno 2] No such file or directory: 'hdfs://localhost:9000/user/hadoop/Projects/PrescPipeline/staging/Dim'
